#!/bin/bash

echo "Compressing /apk-tools/apk-tools into apk-tools-local.tar.xz ..."
tar cfJ ~/aports/main/apk-tools/apk-tools-local.tar.xz -C /apk-tools apk-tools

echo "Replacing apk tools source tarball in APKBUILD at: ~/aports/main/apk-tools/"

if [[ ! -f ~/aports/main/apk-tools/APKBUILD.bak ]]; then
	echo "==> Backing up ~/aports/main/apk-tools/APKBUILD to ~/aports/main/apk-tools/APKBUILD.bak only once..."
	cp ~/aports/main/apk-tools/APKBUILD ~/aports/main/apk-tools/APKBUILD.bak
fi

echo "==> Copying modified APKBUILD in place"
cp /apk-tools/APKBUILD ~/aports/main/apk-tools/APKBUILD

echo "==> Building and installing modified apk-tools"
opwd="$PWD"
cd ~/aports/main/apk-tools
abuild checksum && abuild -ri
cd "$opwd"
